FROM node:20-alpine

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Optional: install ts-node-dev globally
RUN npm install -g ts-node-dev

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
