services:
  app:
    build: .
    container_name: walle-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BANK_API_URL: ${BANK_SERVICE_URL}
    depends_on:
      - db
      - eva-bank
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: walle-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # External bank service -> lo levanto usando la imagen de dockerhub
  eva-bank:
    image: ghcr.io/matichialvaa/eva-bank:latest
    pull_policy: always
    container_name: eva-bank
    ports:
      - "3001:3001"

volumes:
  postgres_data:
