name: Master Workflow

on:
  push:
    branches:
      - master
      - dev

jobs:
  continuous-integration:
    name: continuous integration
    uses: ./.github/workflows/continuous-integration.yml


  continuous-delivery:
    name: continuous delivery
    needs: continuous-integration
    if: github.ref_name == 'master'
    uses: ./.github/workflows/continuous-delivery.yml
    with:
      branch_name: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets:
      WALLE_TOKEN: ${{ secrets.WALLE_TOKEN }}